services:
  - mysql:5.7

image:
  name: jlau/shopware-plugin-test:php7.0
  entrypoint: [""]

build:clone_shopware:
  tags:
    - runner
  script:
    - git clone https://github.com/shopware/shopware.git ${SHOPWARE_DIRECTORY} --branch ${SHOPWARE_VERSION}

build:composer_install:
  tags:
    - runner
  script:
    - composer install --working-dir ${SHOPWARE_DIRECTORY}

build:ant_install:
  tags:
    - runner
  script:
    - ant -f ${SHOPWARE_DIRECTORY}/build/build.xml -Dapp.host=localhost -Ddb.user=root -Ddb.host=mysql -Ddb.password=${MYSQL_ROOT_PASSWORD} -Ddb.name=${MYSQL_DATABASE} build-unit


variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE: yellowbox
  MYSQL_ROOT_PASSWORD: strong_yellowbox_password
  SHOPWARE_VERSION: "5.2"
  PLUGIN_NAME: JodaYellowBox
  SHOPWARE_DIRECTORY: "${HOME}/shopware"
  PLUGIN_DIRECTORY: "${SHOPWARE_DIRECTORY}/custom/plugins"
